# Generated by Django 4.0.6 on 2022-10-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
